stages:
  data_ingestion:
    cmd: python -m src.mlpipeline.pipeline.stage_01_data_ingestion
    deps:
    - src/mlpipeline/components/data_ingestion.py
    - src/mlpipeline/pipeline/stage_01_data_ingestion.py
    - config/config.yaml
    outs:
    - artifacts/data_ingestion/train_data/train.csv
    - artifacts/data_ingestion/test_data/test.csv

  data_validation:
    cmd: python -m src.mlpipeline.pipeline.stage_02_data_validation
    deps:
    - src/mlpipeline/components/data_validation.py
    - src/mlpipeline/pipeline/stage_02_data_validation.py
    - artifacts/data_ingestion/train_data/train.csv
    - artifacts/data_ingestion/test_data/test.csv
    - config/schema.yaml
    outs:
    - artifacts/data_validation/validation_status.txt
    - artifacts/data_validation/data_quality_report.json
    - artifacts/data_validation/drift_report.html

  feature_engineering:
    cmd: python -m src.mlpipeline.pipeline.stage_03_feature_engineering
    deps:
    - src/mlpipeline/components/feature_engineering.py
    - src/mlpipeline/pipeline/stage_03_feature_engineering.py
    - artifacts/data_ingestion/train_data/train.csv
    - artifacts/data_ingestion/test_data/test.csv
    - artifacts/data_validation/validation_status.txt
    - config/feature_config.yaml
    outs:
    - artifacts/feature_engineering/engineered_features/train_featured.csv
    - artifacts/feature_engineering/engineered_features/test_featured.csv
    - artifacts/feature_engineering/feature_importance/feature_importance.csv
    - artifacts/feature_engineering/correlation_analysis/correlation_matrix.csv
    - artifacts/feature_engineering/feature_selection_results/selection_report.json

  data_transformation:
    cmd: python -m src.mlpipeline.pipeline.stage_04_data_transformation
    deps:
    - src/mlpipeline/components/data_transformation.py
    - src/mlpipeline/pipeline/stage_04_data_transformation.py
    - artifacts/feature_engineering/engineered_features/train_featured.csv
    - artifacts/feature_engineering/engineered_features/test_featured.csv
    - config/config.yaml
    outs:
    - artifacts/data_transformation/train.csv
    - artifacts/data_transformation/test.csv
    - artifacts/data_transformation/preprocessor.pkl

  model_trainer:
    cmd: python -m src.mlpipeline.pipeline.stage_05_model_trainer
    deps:
    - src/mlpipeline/components/model_trainer.py
    - src/mlpipeline/pipeline/stage_05_model_trainer.py
    - artifacts/data_transformation/train.csv
    - artifacts/data_transformation/test.csv
    - config/params.yaml
    outs:
    - artifacts/model_trainer/model.pkl

  model_evaluation:
    cmd: python -m src.mlpipeline.pipeline.stage_06_model_evaluation
    deps:
    - src/mlpipeline/components/model_evaluation.py
    - src/mlpipeline/pipeline/stage_06_model_evaluation.py
    - artifacts/model_trainer/model.pkl
    - artifacts/data_transformation/test.csv
    - config/params.yaml
    outs:
    - artifacts/model_evaluation/metrics.json

metrics:
  - artifacts/model_evaluation/metrics.json
