groups:
  - name: ml_pipeline_alerts
    rules:
      # Model Performance Alerts
      - alert: ModelAccuracyLow
        expr: ml_model_accuracy < 0.7
        for: 5m
        labels:
          severity: warning
          component: model
        annotations:
          summary: "Model accuracy has dropped below 70%"
          description: "Current model accuracy is {{ $value }}, which is below the acceptable threshold of 0.7"

      - alert: ModelAccuracyCriticallyLow
        expr: ml_model_accuracy < 0.5
        for: 2m
        labels:
          severity: critical
          component: model
        annotations:
          summary: "Model accuracy critically low"
          description: "Current model accuracy is {{ $value }}, immediate attention required"

      # Data Pipeline Alerts
      - alert: DataIngestionFailure
        expr: increase(ml_data_ingestion_failures_total[5m]) > 0
        for: 0m
        labels:
          severity: critical
          component: data_ingestion
        annotations:
          summary: "Data ingestion pipeline failure detected"
          description: "{{ $value }} data ingestion failures in the last 5 minutes"

      - alert: DataSizeAnomaly
        expr: abs(ml_data_size - ml_data_size offset 1h) > (ml_data_size offset 1h * 0.5)
        for: 10m
        labels:
          severity: warning
          component: data_validation
        annotations:
          summary: "Unusual change in dataset size"
          description: "Dataset size changed by more than 50% compared to 1 hour ago"

      # Training Pipeline Alerts
      - alert: ModelTrainingFailure
        expr: increase(ml_model_training_failures_total[10m]) > 0
        for: 0m
        labels:
          severity: critical
          component: training
        annotations:
          summary: "Model training failure detected"
          description: "{{ $value }} model training failures in the last 10 minutes"

      - alert: LongTrainingTime
        expr: ml_training_duration_seconds > 3600
        for: 0m
        labels:
          severity: warning
          component: training
        annotations:
          summary: "Model training taking longer than expected"
          description: "Current training duration: {{ $value }}s (> 1 hour)"

      # System Resource Alerts
      - alert: HighCPUUsage
        expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 5m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 5 minutes"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 90
        for: 5m
        labels:
          severity: critical
          component: system
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 90% for more than 5 minutes"

      # Application Health Alerts
      - alert: FlaskAppDown
        expr: up{job="flask-app"} == 0
        for: 1m
        labels:
          severity: critical
          component: application
        annotations:
          summary: "Flask application is down"
          description: "The ML prediction service is not responding"

      - alert: MetricsServerDown
        expr: up{job="ml-pipeline-app"} == 0
        for: 2m
        labels:
          severity: warning
          component: monitoring
        annotations:
          summary: "ML pipeline metrics server is down"
          description: "Cannot collect metrics from the ML pipeline application"
