groups:
  - name: ml_pipeline_alerts
    rules:
      - alert: ModelAccuracyLow
        expr: ml_model_accuracy < 0.90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "ML Model accuracy is below 90%"
          description: "Model accuracy is {{ $value }}, which is below the 90% threshold"

      - alert: HighRequestLatency
        expr: histogram_quantile(0.95, http_request_duration_seconds_bucket) > 1.0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High request latency detected"
          description: "95th percentile latency is {{ $value }}s"

      - alert: FlaskAppDown
        expr: up{job="flask-app"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Flask application is down"
          description: "Flask app has been down for more than 1 minute"
