artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  raw_data_dir: artifacts/data_ingestion/raw_data
  train_data_dir: artifacts/data_ingestion/train_data
  test_data_dir: artifacts/data_ingestion/test_data
  competition_name: "playground-series-s5e8"
  local_train_file: "artifacts/data_ingestion/train_data/train.csv"
  local_test_file: "artifacts/data_ingestion/test_data/test.csv"

data_validation:
  root_dir: artifacts/data_validation
  validation_status_file: artifacts/data_validation/validation_status.txt
  drift_report_file: artifacts/data_validation/drift_report.html
  data_quality_report_file: artifacts/data_validation/data_quality_report.json
  use_schema: true
  validation_split: 0.2

feature_engineering:
  root_dir: artifacts/feature_engineering
  engineered_features_dir: artifacts/feature_engineering/engineered_features
  feature_importance_dir: artifacts/feature_engineering/feature_importance
  correlation_analysis_dir: artifacts/feature_engineering/correlation_analysis
  feature_selection_dir: artifacts/feature_engineering/feature_selection_results
  train_data_path: artifacts/data_ingestion/train_data/train.csv
  test_data_path: artifacts/data_ingestion/test_data/test.csv
  processed_train_path: artifacts/feature_engineering/engineered_features/train_featured.csv
  processed_test_path: artifacts/feature_engineering/engineered_features/test_featured.csv
  feature_importance_path: artifacts/feature_engineering/feature_importance/feature_importance.csv
  feature_importance_plot_path: artifacts/feature_engineering/feature_importance/importance_plot.png
  correlation_matrix_path: artifacts/feature_engineering/correlation_analysis/correlation_matrix.csv
  correlation_plot_path: artifacts/feature_engineering/correlation_analysis/correlation_heatmap.png
  feature_selection_report: artifacts/feature_engineering/feature_selection_results/selection_report.json

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: "artifacts/feature_engineering/engineered_features/train_featured.csv"
  preprocessor_obj_file_path: "artifacts/data_transformation/preprocessor.pkl"

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: "artifacts/data_transformation/train.csv"
  test_data_path: "artifacts/data_transformation/test.csv"
  model_name: "model.pkl"
  target_column: "y"
  expected_accuracy: 0.85

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: "artifacts/data_transformation/test.csv"
  model_path: "artifacts/model_trainer/model.pkl"
  metric_file_name: "artifacts/model_evaluation/metrics.json"
  target_column: "y"
  mlflow_uri: "https://dagshub.com/abheshith7/MLOPS_PipeLine.mlflow/"

observability:
  metrics_port: 8000
  jaeger_host: "localhost"
  jaeger_port: 14268
  enable_tracing: true
  enable_metrics: true
  enable_logging: true