RandomForestClassifier:
  n_estimators: 100
  max_depth: 15
  min_samples_split: 5
  min_samples_leaf: 2
  random_state: 42

LogisticRegression:
  C: 1.0
  max_iter: 1000
  random_state: 42

XGBClassifier:
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1
  random_state: 42

feature_engineering:
  numerical_features: ["age", "duration", "campaign", "pdays", "previous", "emp_var_rate", "cons_price_idx", "cons_conf_idx", "euribor3m", "nr_employed"]
  categorical_features: ["job", "marital", "education", "default", "housing", "loan", "contact", "month", "day_of_week", "poutcome"]
  create_interaction_features: true
  scaling_method: "standard"
